namespace lenovo.mbg.service.framework.services;

public enum DownloadStatus
{
	WAITTING,
	DOWNLOADING,
	PAUSE,
	FAILED,
	SUCCESS,
	MD5CHECKFAILED,
	GETFILESIZEFAILED,
	UNENOUGHDISKSPACE,
	CREATEDIRECTORYFAILED,
	DOWNLOADFILENOTFOUND,
	UNDEFINEERROR,
	NETWORKCONNECTIONERROR,
	FILERENAMEFAILED
}
