namespace lenovo.mbg.service.common.utilities;

public enum GlobalCmdType
{
	SWITCHDEVICE,
	AUTO_CLOSE_USB_CONN_TUTORIAL,
	CLOSE_RESCUE_DIALOG,
	DELETE_ROM_AFTER_RESCUE,
	DELETE_ROM_AFTER_RESCUE_RETRY,
	CLOSE_GUID_SETP_DIALOG,
	CLOSE_RESCUE_HELP,
	CLOSE_WIFI_TUTORIAL,
	READ_DEVICEINFO_CALLBACK,
	TABLET_OPEN_USBDEBUG
}
