namespace lenovo.mbg.service.framework.services.Download;

public enum DownloadStatus
{
	WAITTING,
	DOWNLOADING,
	AUTO_PAUSE,
	MANUAL_PAUSE,
	FAILED,
	SUCCESS,
	ALREADYEXISTS,
	DELETED,
	UNZIPPING,
	UNZIPSUCCESS,
	UNZIPFAILED,
	UNZIPNOSPACE,
	MD5CHECKFAILED,
	GETFILESIZEFAILED,
	UNENOUGHDISKSPACE,
	CREATEDIRECTORYFAILED,
	DOWNLOADFILENOTFOUND,
	UNDEFINEERROR,
	NETWORKCONNECTIONERROR,
	FILERENAMEFAILED
}
