namespace lenovo.mbg.service.framework.updateversion.model;

public enum VersionV1Status
{
	VERSION_CHECK_START,
	VERSION_CHECK_HAVE_NEW,
	VERSION_CHECK_HAVE_LATEST,
	VERSION_CHECK_END,
	VERSION_GETDATA_SUCCESS,
	VERSION_GETDATA_FAILED,
	VERSION_DOWNLOADING,
	VERSION_DOWNLOADING_PERCENT,
	VERSION_DOWNLOADING_SUCCESS,
	VERSION_DOWNLOADING_FAILED,
	VERSION_INSTALL_START,
	VERSION_INSTALL_BACKUP,
	VERSION_INSTALL_BACKUP_PERCENT,
	VERSION_INSTALL_ROLLBACK,
	VERSION_INSTALL_ROLLBACK_PERCENT,
	VERSION_INSTALL_ROLLBACK_SUCCESS,
	VERSION_INSTALL_ROLLBACK_FAILED,
	VERSION_INSTALL_PERCENT,
	VERSION_INSTALL_SUCCESS,
	VERSION_INSTALL_FAILED,
	VERSION_EXCEPTION
}
